from datetime import datetime


def _leader_name(entry):
    """Safely pulls the name out of a top_contractor/top_defect entry.

    `entry` is a dict like {"name": ..., "count": ..., "share_pct": ...},
    or None if there was no data for the period (e.g. a zero-rework week).
    """
    return entry["name"] if entry else "N/A"


def build_weekly_email(statistics):

    subject = (
        f"### REWORKIQ TEST BUILD ### | "
        f"{datetime.now().strftime('%d %b %Y')}"
    )

    body = f"""
Dear Team,

Please find attached the Weekly Rework Performance Report generated by ReworkIQ.

Reporting Period
----------------------------------

Last 7 Days

Summary
----------------------------------

Total Reworks :
{statistics["total_reworks"]}

Plants Covered :
{statistics["plants_covered"]}

Contractors Involved :
{statistics["contractors"]}

Defect Types :
{statistics["defect_types"]}

Top Contractor :
{_leader_name(statistics.get("top_contractor"))}

Most Frequent Defect :
{_leader_name(statistics.get("top_defect"))}

Please find the attached PDF report.

Regards,

ReworkIQ
Quality Analytics System
"""

    return subject, body


# =========================================================
# MANUAL TEST
# =========================================================

if __name__ == "__main__":
    normal_week = {
        "total_reworks": 47,
        "plants_covered": 3,
        "contractors": 6,
        "defect_types": 5,
        "top_contractor": {"name": "Corimpex Welding Co.", "count": 15, "share_pct": 31.9},
        "top_defect": {"name": "Porosity", "count": 16, "share_pct": 34.0},
    }
    print("--- Normal week ---")
    subject, body = build_weekly_email(normal_week)
    print(subject)
    print(body)

    zero_week = {
        "total_reworks": 0,
        "plants_covered": 0,
        "contractors": 0,
        "defect_types": 0,
        "top_contractor": None,
        "top_defect": None,
    }
    print("--- Zero-rework week (previously would have crashed) ---")
    subject, body = build_weekly_email(zero_week)
    print(subject)
    print(body)