"""ReworkIQ Version 2.0

Revision ID: f60181a23574
Revises: fc1e067c62e2
Create Date: 2026-07-02 09:25:08.153334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60181a23574'
down_revision = 'fc1e067c62e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rework_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('defect_code', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('inspection_date', sa.Date(), nullable=False))
        batch_op.drop_column('project_name')
        batch_op.drop_column('rework_date')
        batch_op.drop_column('reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rework_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('rework_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('inspection_date')
        batch_op.drop_column('remarks')
        batch_op.drop_column('defect_code')
        batch_op.drop_column('plant')

    # ### end Alembic commands ###
