"""Create rework_entries table

Revision ID: fc1e067c62e2
Revises: 
Create Date: 2026-06-29 10:26:27.034908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1e067c62e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rework_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mark_no', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=150), nullable=False),
    sa.Column('contractor', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=150), nullable=False),
    sa.Column('rework_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rework_entries')
    # ### end Alembic commands ###
